### ISSUE TITLE
Issuing a `touch` on a file rebuilds the binary 2 times in a row

### ISSUE THREAD

**Issue by mikegleasonjr** [githubnemo/CompileDaemon#13]
I have something like:

```
CompileDaemon -build="go build -o bin/darwin-amd64/x x/x.go" -command="./bin/darwin-amd64/x" -pattern=".+\.go$"
```

If I do a simple `touch x.go` the binary gets compiled twice...

**EDIT:** Actually, starting it simply like this does the same problem:

```
CompileDaemon --exclude-dir=vendor
```

**Comment by mikegleasonjr** [comment]
Using github.com/currantlabs/CompileDaemon resolves my problem

**Comment by githubnemo** [comment]
Thanks for reporting. CompileDaemon does not filter the FS events so a write and a close will both toggle the build. The fork you referenced solves this by adding such a filter, see https://github.com/currantlabs/CompileDaemon/commit/0866a6f6b8d54948cf17d3f1fca36db66bf4d448.

I'm not sure when I can implement this since I'm rather busy at the moment.

**Comment by githubnemo** [comment]
Should be fixed in cbc867336f498b

**Comment by Justin-Marks** [comment]
Still getting two binaries after `CompileDaemon -command="mybinary.exe"`. Go edit a file and it creates two binaries `mybinary.exe` and `mybinary.exe~`

**Comment by githubnemo** [comment]
What do you mean? Running a command does not produce binaries. When editing a file yields two file events because it edits the original and creates a backup file, then you should fix your matching regular expression to compensate (e.g. do not match on `.*\.go` but match on `.*\.go$`).

**Comment by Justin-Marks** [comment]
The regexp doesn't seem to make a difference.

Before
```
app/
    main.go
```

```
>CompileDaemon -command="app.exe"                                                           
2016/09/26 19:12:44 Running build command!                                                                                     
2016/09/26 19:12:45 Build ok.                                                                                                  
2016/09/26 19:12:45 Restarting the given command.                                                                              
2016/09/26 19:12:55 Running build command!                                                                                     
2016/09/26 19:12:56 Build ok.                                                                                                  
2016/09/26 19:12:56 Hard stopping the current process..                                                                        
2016/09/26 19:12:56 Restarting the given command.
```
After
```
app/
    app.exe
    app.exe~
    main.go
```
main.go
```
package main

import "net/http"

func main() {
    http.ListenAndServe(":8080", nil)
}
```

**Comment by githubnemo** [comment]
CompileDaemon does not create files or copies files. I have no idea where the `app.exe~` file comes from but I'm pretty sure that it is not due to CompileDaemon, sorry.

**Comment by mikegleasonjr** [comment]
@Justin-Marks This is not the same issue (if issue there is)

**Comment by Justin-Marks** [comment]
My mistake. This wasn't caused by CompileDaemon. Probably a bug with https://golang.org/src/cmd/go/build.go `copyFile()` method.
